version: "3"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # TODO pass
      MYSQL_ROOT_PASSWORD: safe-password
      MYSQL_DATABASE: rust_database
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mysql-phpmyadmin
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: safe-password
    networks:
      - mysql-phpmyadmin
     
networks:
  mysql-phpmyadmin:

volumes:
  mysqldata:
